apiVersion: v1
kind: Namespace
metadata:
  name: ai-search
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-search-userdict-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/davidnam/Project/pulmuone/ai-search-gpt/.local-nas/userdict
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-search-userdict-pvc
  namespace: ai-search
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: ai-search-userdict-pv
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ai-search-es
  namespace: ai-search
spec:
  version: 8.13.4
  image: ai-search-es:8.13.4-nori
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
        xpack.license.self_generated.type: basic
      podTemplate:
        spec:
          volumes:
            - name: userdict-volume
              persistentVolumeClaim:
                claimName: ai-search-userdict-pvc
          containers:
            - name: elasticsearch
              volumeMounts:
                - name: userdict-volume
                  mountPath: /usr/share/elasticsearch/config/userdict
              resources:
                requests:
                  memory: 2Gi
                  cpu: "500m"
                limits:
                  memory: 2Gi
                  cpu: "2000m"
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms1g -Xmx1g"
